services:
  bot-whatsapp:
    build:
      context: .
    container_name: bot-whatsapp
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - bot_session:/app/.session
      - bot_cache:/app/.wwebjs_cache

volumes:
  bot_session:
  bot_cache:
